server:
  port: 8089
  servlet:
    context-path: /payment

spring:
  application:
    name: payment-service
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mariadb://mariadb:3306/payment_db}
    driver-class-name: "org.mariadb.jdbc.Driver"
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:sapassword}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
vnpay:
  tmnCode: VRIAH5CW
  hashSecret: 0GX6EJ0RU7DA1GQDRAJTN6JLSK50NWD9
  payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  returnUrl: http://localhost:8089/payment/vn-pay-callback
  ipnUrl: https://your-domain.com/api/payment/vnpay-ipn
  apiUrl: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
  orderType: orther
  command: pay
  version: 2.1.0