server:
  port: 8089
  servlet:
    context-path: /payment

spring:
  application:
    name: payment-service
  kafka:
    bootstrap-servers: ${DBKK_CONNECTION:kafka}:9094
    consumer:
      group-id: payment-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mariadb://mariadb:3306/payment_db}
    driver-class-name: "org.mariadb.jdbc.Driver"
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:sapassword}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

logging:
  level:
    iuh.fit.se: DEBUG
    org.hibernate.SQL: DEBUG
vnpay:
  tmnCode: ${VNPAY_TMN_CODE:VRIAH5CW}
  hashSecret: ${VNPAY_HASH_SECRET:0GX6EJ0RU7DA1GQDRAJTN6JLSK50NWD9}
  payUrl: ${VNPAY_PAY_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
  returnUrl: ${VNPAY_RETURN_URL:http://localhost:8888/shopping/api/payment/vn-pay-callback}
  ipnUrl: ${VNPAY_IPN_URL:http://localhost:8888/shopping/api/payment/vnpay-ipn}
  apiUrl: ${VNPAY_API_URL:https://sandbox.vnpayment.vn/merchant_webapi/api/transaction}
  orderType: ${VNPAY_ORDER_TYPE:other}
  command: ${VNPAY_COMMAND:pay}
  version: ${VNPAY_VERSION:2.1.0}